### ISSUE TITLE
Add define( 'DOING_AJAX', true ) to the endpoint mechanism

### ISSUE THREAD

**Issue by nickchomey** [dannyvankooten/plugin-endpoints#13]
Without this, mechanisms (buddypress in my case) that check to see if AJAX is called don't work. I can't really foresee how defining this would ever interfere negatively with anyone's site.

Pull request https://github.com/dannyvankooten/plugin-endpoints/pull/12 solves this.

**Comment by dannyvankooten** [comment]
Hello @nickchomey,

How exactly are you using this mu-plugin?

It should not be necessary to set any WP routing related constants if you just keep on using the same URL’s as the plugins in question expect. For AJAX endpoints using admin-ajax.php you can include the action query arg to only act on a specific endpoint.

If that is no option I recommend adding some additional code that only sets the additional constants and stuff for that specific endpoint. I am afraid we can’t just set it for every custom endpoint defined using this plugin because of the unforeseen consequences. Many plugins use DOING_AJAX to conditionally load or not load some parts of their plugin so I can very well see including this change leading to some hard-to-track down issues.

**Comment by nickchomey** [comment]
I should have been more clear - I have a custom plugin that is using a custom endpoint with your plugin, and it calls various buddypress functions. But the buddypress global objects only load properly when DOING_AJAX is set. I want to avoid admin-Ajax for various reasons. 

Anyway, I understand your objection to adding this. I'll add a customization to either the plugin or just a separate function in my plugin that hooks into init and sets DOING_AJAX.

Thanks for the quick reply and even moreso for sharing this plugin!
